CREATE TABLE TEAM (
    TeamID INT AUTO_INCREMENT PRIMARY KEY,
    TeamName VARCHAR(30)
);

CREATE TABLE INNING_PART (
    inningPartId INT AUTO_INCREMENT PRIMARY KEY,
    inningPartName VARCHAR(10)
);

CREATE TABLE EVENT (
    eventID INT AUTO_INCREMENT PRIMARY KEY,
    eventName VARCHAR(50),
    eventCode INT
);

CREATE TABLE PLAYER(
	PlayerID INT AUTO_INCREMENT PRIMARY KEY,
	PlayerNum INT 
);

CREATE TABLE POS(
	PositionID INT AUTO_INCREMENT PRIMARY KEY,
	PosCode INT,
	PosName VARCHAR(30)
);

CREATE TABLE GAME (
    gameId INT AUTO_INCREMENT PRIMARY KEY,
    date Date,
    home INT,
    away INT,
    FOREIGN KEY (home) REFERENCES TEAM(TeamID),
    FOREIGN KEY (away) REFERENCES TEAM(TeamID)
);

Create table INNING (
	inningId INT AUTO_INCREMENT PRIMARY KEY,
	inningNumber INT,
    inningPartId INT,
    gameId INT,
    FOREIGN KEY (inningPartId) REFERENCES INNING_PART(inningPartId),
	FOREIGN KEY (gameID) REFERENCES GAME(gameId)
);

CREATE TABLE PLAY (
    playId INT PRIMARY KEY,
    playPerGame INT,
    inningId INT,
    FOREIGN KEY (inningId) REFERENCES INNING(InningID)
);

CREATE TABLE PLAY_EVENT (
    playEventID INT AUTO_INCREMENT PRIMARY KEY,
    eventID INT,
    playID INT,
    FOREIGN KEY (eventID) REFERENCES EVENT(eventID),
    FOREIGN KEY (playID) REFERENCES PLAY(playID)
);

CREATE TABLE TEAM_PLAYER(
	TeamPlayerID INT AUTO_INCREMENT PRIMARY KEY,
    PlayerID INT,
    TeamID INT,
	FOREIGN KEY (PlayerID) REFERENCES PLAYER(PlayerID),
	FOREIGN KEY (TeamID) REFERENCES TEAM(TeamID)
);

CREATE TABLE PLAYER_PLAY(
	PlayerPlayID INT AUTO_INCREMENT PRIMARY KEY,
    PlayID INT,
    PositionID INT,
    PlayerID INT,
	FOREIGN KEY (PlayID) REFERENCES PLAY(PlayID),
	FOREIGN KEY(PositionID) REFERENCES POS(PositionID),
	FOREIGN KEY (PlayerID) REFERENCES PLAYER(PlayerID)
);

CREATE TABLE PLAYER_MOMENT(
	PlayerMomentID INT AUTO_INCREMENT PRIMARY KEY,
	TimeStamp INT,
	FieldX NUMERIC(8,4),
	FieldY NUMERIC(8,4),
    PlayerPlayID INT,
    FOREIGN KEY (PlayerPlayID) REFERENCES  PLAYER_PLAY(PlayerPlayID)
);

CREATE TABLE BALL_POS(
	BallPosID INT AUTO_INCREMENT PRIMARY KEY,
	TimeStamp INT,
	BallPositionX NUMERIC(8,4),
	BallPositionY NUMERIC(8,4),
	BallPositionZ NUMERIC(8,4),
    PlayID INT,
    FOREIGN KEY (PlayID) REFERENCES PLAY(PlayID)
)


